import type { Tool } from '../types';

export const tools: Tool[] = [
  {
    name: 'ChatGPT',
    description: 'Assistente conversacional para escrever, explicar conceitos, organizar ideias e trabalhar com diferentes tipos de entrada.',
    category: 'Chatbots',
    use: 'rascunhos, brainstorming, estudos e análise de textos',
    level: 'Iniciante',
    url: 'https://chatgpt.com/',
    accent: '#e6f5f1',
  },
  {
    name: 'Gemini',
    description: 'Assistente do Google para conversar, pesquisar ideias e apoiar tarefas de escrita, análise e planejamento.',
    category: 'Chatbots',
    use: 'pesquisa inicial, planejamento e síntese de informações',
    level: 'Iniciante',
    url: 'https://gemini.google.com/',
    accent: '#e9efff',
  },
  {
    name: 'Claude',
    description: 'Assistente da Anthropic com foco em conversas longas, redação, análise e organização de documentos.',
    category: 'Chatbots',
    use: 'revisão de textos extensos, análise e programação',
    level: 'Iniciante',
    url: 'https://claude.ai/',
    accent: '#f7eee5',
  },
  {
    name: 'Perplexity',
    description: 'Ferramenta de pesquisa que combina respostas em linguagem natural com referências para continuar a investigação.',
    category: 'Pesquisa',
    use: 'levantar fontes e comparar informações de um tema',
    level: 'Iniciante',
    url: 'https://www.perplexity.ai/',
    accent: '#e8f5f7',
  },
  {
    name: 'Canva AI',
    description: 'Recursos de inteligência artificial integrados ao Canva para criar e editar peças visuais dentro do editor.',
    category: 'Imagem',
    use: 'posts, apresentações e variações visuais para conteúdo',
    level: 'Iniciante',
    url: 'https://www.canva.com/ai-image-generator/',
    accent: '#eeeafd',
  },
  {
    name: 'Adobe Firefly',
    description: 'Família de recursos generativos da Adobe para criar e editar imagens e elementos visuais.',
    category: 'Imagem',
    use: 'ideias visuais, preenchimento generativo e variações',
    level: 'Intermediário',
    url: 'https://firefly.adobe.com/',
    accent: '#fff0e5',
  },
  {
    name: 'Runway',
    description: 'Plataforma criativa com ferramentas para experimentação e produção de vídeo assistida por IA.',
    category: 'Vídeo',
    use: 'storyboards, testes visuais e edição generativa',
    level: 'Intermediário',
    url: 'https://runwayml.com/',
    accent: '#f0edf9',
  },
  {
    name: 'ElevenLabs',
    description: 'Plataforma de áudio com recursos de voz sintética e ferramentas para criação de fala.',
    category: 'Áudio',
    use: 'narração, protótipos de voz e acessibilidade',
    level: 'Intermediário',
    url: 'https://elevenlabs.io/',
    accent: '#f1f3f7',
  },
  {
    name: 'GitHub Copilot',
    description: 'Assistente de programação integrado ao fluxo de desenvolvimento para sugerir código e explicar trechos.',
    category: 'Programação',
    use: 'boilerplate, testes, explicação e refatoração assistida',
    level: 'Intermediário',
    url: 'https://github.com/features/copilot',
    accent: '#e9edf5',
  },
  {
    name: 'Notion AI',
    description: 'Recursos de IA dentro do espaço de trabalho do Notion para escrever, resumir e organizar páginas.',
    category: 'Produtividade',
    use: 'atas, planos, documentação e organização de projetos',
    level: 'Iniciante',
    url: 'https://www.notion.so/product/ai',
    accent: '#f2f2f2',
  },
];
